import type { BlogPost } from "@/lib/blog/types";

export const postsActualites: BlogPost[] = [
  {
    slug: "journees-patrimoine-montpellier-2026",
    title: "Journées européennes du patrimoine 2026 : Montpellier ouvre ses portes",
    metaTitle: "Journées du patrimoine Montpellier 2026 | A6",
    metaDescription: "Les 19 et 20 septembre 2026, découvrez le patrimoine de Montpellier et de sa métropole : visites insolites, lieux ouverts et rendez-vous culturels.",
    keyword: "journées du patrimoine Montpellier 2026",
    category: "Événementiel",
    date: "2026-09-12",
    dateLabel: "12 septembre 2026",
    readingMinutes: 1,
    img: "/photos/cardstack-blog-v2.webp",
    imgAlt: "Photographie d’illustration du blog A6 Communication",
    excerpt: "Les 19 et 20 septembre, les Journées européennes du patrimoine invitent à découvrir Montpellier et sa métropole autrement, à travers des visites et des ouvertures exceptionnelles.",
    body: [
      { kind: "p", text: "La 43e édition des Journées européennes du patrimoine se tiendra les samedi 19 et dimanche 20 septembre 2026. À Montpellier et dans les communes de la métropole, elle permettra notamment d’accéder à des lieux habituellement fermés au public." },
      { kind: "h2", id: "programme", text: "Des découvertes au fil du territoire" },
      { kind: "p", text: "Cette édition met à l’honneur le patrimoine de la photographie et le patrimoine en péril. Parmi les rendez-vous annoncés : les Archives de Montpellier, les ateliers de La Costumotek et la Banque de France. À Jacou, le Domaine de Bocaud et ses jardins se découvrent en visite ; à Castries, la réouverture du château figure aussi au programme." },
      { kind: "h2", id: "preparer", text: "Préparer sa visite" },
      { kind: "p", text: "Les modalités varient selon les lieux : certaines visites nécessitent une réservation et toutes ne sont pas gratuites. Consultez les horaires et conditions avant de vous déplacer." },
      { kind: "p", text: "Retrouvez la sélection et les liens de réservation dans [l’article d’En Commun, publié le 7 septembre 2026](https://encommun.montpellier.fr/articles/2026-09-07-journees-europeennes-du-patrimoine-jep-temps-forts-et-visites-insolites)." },
    ],
  },
  {
    slug: "gilbert-comos-reelu-president-ffb-herault",
    title: "Gilbert Comos réélu à la présidence de la FFB Hérault pour trois ans",
    metaTitle: "Gilbert Comos réélu à la FFB Hérault | A6",
    metaDescription: "Réélu pour trois ans, Gilbert Comos poursuit son engagement à la FFB Hérault : proximité avec les adhérents et défense des entreprises du bâtiment.",
    keyword: "Gilbert Comos FFB Hérault",
    category: "Institutionnel",
    date: "2026-09-12",
    dateLabel: "12 septembre 2026",
    readingMinutes: 2,
    img: "/photos/nos-clients/professionnels-batir-v2.webp",
    imgAlt: "Photographie d’illustration de la rubrique professionnels du bâtiment d’A6",
    excerpt: "Le Conseil d’administration de la FFB Hérault renouvelle sa confiance à Gilbert Comos pour un mandat de trois ans, placé sous le signe de la proximité et de l’action collective.",
    body: [
      { kind: "p", text: "Le Conseil d’administration de la Fédération Française du Bâtiment de l’Hérault a réélu Gilbert Comos à sa présidence pour un nouveau mandat de trois ans. Cette confiance renouvelée permet de poursuivre le travail engagé auprès des entreprises du bâtiment du département." },
      { kind: "h2", id: "terrain", text: "Une connaissance concrète du terrain" },
      { kind: "p", text: "Chef d’entreprise et homme de terrain, Gilbert Comos connaît les réalités du métier, ses contraintes et la passion qui anime les entrepreneurs. Son engagement fédéral repose sur une conviction : l’action collective renforce la représentation des entreprises et la défense de leurs intérêts." },
      { kind: "h2", id: "proximite", text: "La proximité avec les adhérents au cœur de l’action" },
      { kind: "p", text: "Rencontrer les entreprises, écouter leurs préoccupations et favoriser les échanges constituent des priorités de son engagement. Cette présence auprès des adhérents nourrit aussi le dialogue avec les acteurs du territoire, auprès desquels la Fédération porte la voix des professionnels." },
      { kind: "h2", id: "collectif", text: "Un nouveau mandat porté par un collectif" },
      { kind: "p", text: "Cette dynamique s’appuie sur l’implication des élus, des mandataires et de l’équipe de la FFB Hérault. Ensemble, ils contribuent à faire vivre une Fédération proche de ses adhérents, engagée et utile aux entreprises, capable de rassembler et de défendre les intérêts du bâtiment dans l’Hérault." },
      { kind: "p", text: "Félicitations à Gilbert Comos pour ce nouveau mandat et pour la confiance renouvelée du Conseil d’administration." },
    ],
  },
];
